version: '2'

services:
  nginx:
    container_name: angular-nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../dist:/usr/share/nginx/html
